version: '2'
services:
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    environment:
      - CORE_LOGGING_PEER= debug
      - CORE_CHAINCODE_LOGGING_LEVEL= DEBUG
      - 'CORE_VM_ENDPOINT= unix:///host/var/run/docker.sock'
      - CORE_PEER_ID= peer3.org4.example.com
      - 'CORE_PEER_ADDRESS= peer3.org4.example.com:7051'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=pershing
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=./msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051'
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=./tls/server.key
      - CORE_PEER_TLS_CERT_FILE=./tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=./tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - '7051:7051'
      - '7053:7053'
